In [225]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sb

In [226]:
df = pd.read_csv('data/new_diamonds.csv')
df

carat        cut color clarity  depth  table  price     x     y     z  \
0       0.23  Excellent     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21  Very Good     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Fair     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29  Very Good     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Fair     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
49995   0.72  Excellent     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
49996   0.72       Fair     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
49997   0.70       Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
49998   0.86  Very Good     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
49999   0.75  Excellent     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

       type  
0         0  
1         1  
2         1  
3         1  
4         0  
...     ...  
49995     0  
49996     0  
49997     1  
49998     1  
49999     0  

[50000 rows x 11 columns]

In [227]:
X = df.drop(['price', 'x', 'y', 'type'], axis=1)
X

carat        cut color clarity  depth  table     z
0       0.23  Excellent     E     SI2   61.5   55.0  2.43
1       0.21  Very Good     E     SI1   59.8   61.0  2.31
2       0.23       Fair     E     VS1   56.9   65.0  2.31
3       0.29  Very Good     I     VS2   62.4   58.0  2.63
4       0.31       Fair     J     SI2   63.3   58.0  2.75
...      ...        ...   ...     ...    ...    ...   ...
49995   0.72  Excellent     D     SI1   60.8   57.0  3.50
49996   0.72       Fair     D     SI1   63.1   55.0  3.61
49997   0.70       Good     D     SI1   62.8   60.0  3.56
49998   0.86  Very Good     H     SI2   61.0   58.0  3.74
49999   0.75  Excellent     D     SI2   62.2   55.0  3.64

[50000 rows x 7 columns]

In [228]:
y = df['type'].to_frame()
y

type
0         0
1         1
2         1
3         1
4         0
...     ...
49995     0
49996     0
49997     1
49998     1
49999     0

[50000 rows x 1 columns]

In [229]:
from sklearn.preprocessing import LabelEncoder
from pandas.api.types import is_integer_dtype, is_float_dtype, is_object_dtype

In [230]:
X_new = pd.DataFrame()
for col in X:
    if is_object_dtype(X[col]):
        encoder = LabelEncoder()
        X_new[col] = encoder.fit_transform(X[col])
    else :
        X_new[col] = X[col]

In [231]:
X_new

carat  cut  color  clarity  depth  table     z
0       0.23    0      1        3   61.5   55.0  2.43
1       0.21    4      1        2   59.8   61.0  2.31
2       0.23    1      1        4   56.9   65.0  2.31
3       0.29    4      5        5   62.4   58.0  2.63
4       0.31    1      6        3   63.3   58.0  2.75
...      ...  ...    ...      ...    ...    ...   ...
49995   0.72    0      0        2   60.8   57.0  3.50
49996   0.72    1      0        2   63.1   55.0  3.61
49997   0.70    2      0        2   62.8   60.0  3.56
49998   0.86    4      4        3   61.0   58.0  3.74
49999   0.75    0      0        3   62.2   55.0  3.64

[50000 rows x 7 columns]

#### 피쳐 스케일링

In [232]:
from sklearn.preprocessing import StandardScaler

In [233]:
scaler = StandardScaler()

In [234]:
X_scaled = scaler.fit_transform(X_new)
X_scaled

array([[-1.1984046 , -1.02142904, -0.94023721, ..., -0.17679459,
        -1.10114407, -1.57137967],
       [-1.24049496,  1.44955104, -0.94023721, ..., -1.36471424,
         1.58694437, -1.74109709],
       [-1.1984046 , -0.40368402, -0.94023721, ..., -3.39116541,
         3.37900333, -1.74109709],
       ...,
       [-0.20928124,  0.214061  , -1.52833389, ...,  0.73161456,
         1.13892963,  0.02679272],
       [ 0.1274416 ,  1.44955104,  0.82405283, ..., -0.52618272,
         0.24290015,  0.28136886],
       [-0.10405536, -1.02142904, -1.52833389, ...,  0.3123488 ,
        -1.10114407,  0.13993767]])

#### 데이터 분할

In [235]:
from sklearn.model_selection import train_test_split

In [236]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size = 0.2, random_state = 4)

#### KNN 통해 신규 데이터 분류

In [237]:
from sklearn.neighbors import KNeighborsClassifier

In [238]:
classifier = KNeighborsClassifier(n_neighbors = 5)

In [239]:
classifier.fit(X_train, y_train)

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

#### y 계산

In [240]:
y_pred = classifier.predict(X_test)

In [241]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [242]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2757,   27,   15],
       [  19, 3949,   12],
       [  12,   19, 3190]])

In [243]:
accuracy_score(y_test, y_pred)

0.9896

In [244]:
import joblib

In [245]:
joblib.dump(classifier, 'model/classifier.pkl')

['model/classifier.pkl']

In [246]:
X_new.loc[df['type']==0, :].describe()

carat           cut         color       clarity         depth  \
count  14186.000000  14186.000000  14186.000000  14186.000000  14186.000000   
mean       0.863914      0.924996      2.680883      2.293881     62.366552   
std        0.486018      1.177937      1.747920      0.846973      1.338895   
min        0.210000      0.000000      0.000000      0.000000     56.500000   
25%        0.440000      0.000000      1.000000      2.000000     61.600000   
50%        0.770000      0.000000      3.000000      2.000000     62.200000   
75%        1.090000      2.000000      4.000000      3.000000     63.100000   
max        5.010000      4.000000      6.000000      5.000000     78.200000   

              table             z  
count  14186.000000  14186.000000  
mean      56.220852      3.672826  
std        1.291319      0.728677  
min       49.000000      0.000000  
25%       55.000000      3.060000  
50%       56.000000      3.660000  
75%       57.000000      4.100000  
max       61.000000     31.800000

In [247]:
X_new.loc[df['type']==1, :].describe()

carat           cut         color       clarity         depth  \
count  19684.000000  19684.000000  19684.000000  19684.000000  19684.000000   
mean       0.902303      3.108007      2.689697      3.688072     61.187376   
std        0.503784      1.168399      1.741144      1.565043      1.598026   
min        0.200000      0.000000      0.000000      0.000000     43.000000   
25%        0.450000      2.000000      1.000000      2.000000     60.200000   
50%        0.900000      4.000000      3.000000      4.000000     61.300000   
75%        1.160000      4.000000      4.000000      5.000000     62.300000   
max        4.130000      4.000000      6.000000      7.000000     79.000000   

              table             z  
count  19684.000000  19684.000000  
mean      59.562863      3.664102  
std        1.705277      0.712329  
min       55.000000      0.000000  
25%       58.000000      3.000000  
50%       59.000000      3.760000  
75%       60.000000      4.130000  
max       95.000000      8.060000

In [248]:
X_new.loc[df['type']==2, :].describe()

carat           cut         color       clarity         depth  \
count  16130.000000  16130.000000  16130.000000  16130.000000  16130.000000   
mean       0.617221      0.519157      2.415623      5.374458     61.903664   
std        0.364271      0.949613      1.589687      1.048583      0.954731   
min        0.200000      0.000000      0.000000      3.000000     43.000000   
25%        0.330000      0.000000      1.000000      5.000000     61.400000   
50%        0.510000      0.000000      2.000000      5.000000     61.900000   
75%        0.760000      1.000000      3.000000      6.000000     62.400000   
max        2.500000      4.000000      6.000000      7.000000     67.600000   

              table             z  
count  16130.000000  16130.000000  
mean      55.976882      3.275009  
std        1.217544      0.599216  
min       43.000000      0.000000  
25%       55.000000      2.750000  
50%       56.000000      3.170000  
75%       57.000000      3.630000  
max       60.200000      5.380000

#### 신규 데이터 투입

In [249]:
X

carat        cut color clarity  depth  table     z
0       0.23  Excellent     E     SI2   61.5   55.0  2.43
1       0.21  Very Good     E     SI1   59.8   61.0  2.31
2       0.23       Fair     E     VS1   56.9   65.0  2.31
3       0.29  Very Good     I     VS2   62.4   58.0  2.63
4       0.31       Fair     J     SI2   63.3   58.0  2.75
...      ...        ...   ...     ...    ...    ...   ...
49995   0.72  Excellent     D     SI1   60.8   57.0  3.50
49996   0.72       Fair     D     SI1   63.1   55.0  3.61
49997   0.70       Good     D     SI1   62.8   60.0  3.56
49998   0.86  Very Good     H     SI2   61.0   58.0  3.74
49999   0.75  Excellent     D     SI2   62.2   55.0  3.64

[50000 rows x 7 columns]

In [250]:
sorted(X['cut'].unique())

['Excellent', 'Fair', 'Good', 'Poor', 'Very Good']

In [251]:
sorted(X['color'].unique())

['D', 'E', 'F', 'G', 'H', 'I', 'J']

In [252]:
sorted(X['clarity'].unique())

['I1', 'IF', 'SI1', 'SI2', 'VS1', 'VS2', 'VVS1', 'VVS2']

In [253]:
data = np.array([0.26, 'Excellent', 'D', 'SI2',63.0, 55, 3.64]).reshape(1, 7)
data

array([['0.26', 'Excellent', 'D', 'SI2', '63.0', '55', '3.64']],
      dtype='<U32')

In [254]:
data = pd.DataFrame(data)
data

0          1  2    3     4   5     6
0  0.26  Excellent  D  SI2  63.0  55  3.64

In [255]:
data[1] = 3
data[2] = 6
data[3] = 0

In [256]:
classifier.predict(data)

/opt/anaconda3/envs/hi/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])